CREATE TABLE MESSAGES(
    MSG_SEQ SERIAL PRIMARY KEY,
    MSG_TITLE VARCHAR(50) NOT NULL,
    MSG_BODY VARCHAR(2000) NOT NULL,
    MSG_SEND_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MSG_SND_SEQ BIGINT NOT NULL,
    MSG_RCV_SEQ BIGINT NOT NULL,
    FOREIGN KEY (MSG_SND_SEQ) REFERENCES USERS(USER_SEQ),
    FOREIGN KEY (MSG_RCV_SEQ) REFERENCES USERS(USER_SEQ)
)