CREATE TABLE comments(
    CMT_SEQ SERIAL PRIMARY KEY,
    USER_SEQ BIGINT NOT NULL,
    POST_SEQ BIGINT NOT NULL,
    CMT_BODY VARCHAR(255) NOT NULL,
    CMT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY(USER_SEQ) REFERENCES USERS(USER_SEQ),
    FOREIGN KEY(POST_SEQ) REFERENCES POSTS(POST_SEQ)
);