CREATE TABLE POST(
    POST_SEQ SERIAL PRIMARY KEY,
    USER_SEQ BIGINT NOT NULL,
    CLUB_SEQ BIGINT NOT NULL,
    POST_TITLE VARCHAR(255) NOT NULL,
    POST_BODY VARCHAR(1000) NOT NULL,
    POST_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    POST_ATMT_URL VARCHAR(1000) NULL,
    FOREIGN KEY(USER_SEQ) REFERENCES USERS(USER_SEQ),
    FOREIGN KEY(CLUB_SEQ) REFERENCES CLUBS(CLUB_SEQ)
);