CREATE TYPE AUTH AS ENUM ('GENERAL','GOOGLE','KAKAO','FACEBOOK');

CREATE TABLE USERS(
    USER_SEQ SERIAL PRIMARY KEY,
    USER_ID VARCHAR(20) NOT NULL,
    USER_NAME VARCHAR(20) NOT NULL,
    USER_PN VARCHAR(20) NOT NULL,
    USER_EMAIL VARCHAR(100) NOT NULL,
    USER_LST_CNN_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USER_AUTH AUTH
)