CREATE TABLE CHATS(
    CHAT_SEQ SERIAL PRIMARY KEY,
    CLUB_SEQ INTEGER NOT NULL,
    USER_SEQ INTEGER NOT NULL,
    CHAT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHAT_CONTENT VARCHAR(255) NOT NULL,
    FOREIGN KEY (USER_SEQ) REFERENCES USERS(USER_SEQ),
    FOREIGN KEY (CLUB_SEQ) REFERENCES CLUBS(CLUB_SEQ)
);
