CREATE TABLE ACCOUNT(
    ACCOUNT_NUM VARCHAR(50) PRIMARY KEY,
    ACCOUNT_NAME VARCHAR(30) NOT NULL,
    ACCOUNT_OWNER VARCHAR(20) NOT NULL,
    ACCOUNT_BNAME VARCHAR(20) NOT NULL,
    ACCOUNT_BAL BIGINT NOT NULL DEFAULT 0,
    CLUB_SEQ SERIAL NOT NULL,
    FOREIGN KEY(CLUB_SEQ) REFERENCES CLUB(CLUB_SEQ)
)